#%RAML 1.0 NamedExample
routeexamples:
  [
    {
      "companycode": "Transational",
      "originlocation": {
        "locationcode": "BEN-SG", "locationDesc":
            "Beauna Vista Singapore"
      },
      "destinationLocation":{
        "locationcode": "KLG-MY",
        "locationDesc": "klang Malaysia"

    }


    }, {
      "companycode": "Transational",
      "originlocation": {
        "locationcode": "BEN-SG", "locationDesc":
            "Beauna Vista Singapore"
      },
      "destinationLocation":{
        "locationcode": "KLG-MY",
        "locationDesc": "klang Malaysia"

    }
    }
  ]